#!/bin/bash
# Grab an ARP list using arp-scan and chop off the top 2 lines and bottom 3 lines and reformat with awk for JSON parsing print everything to Stdout
arp-scan --localnet --interface=$1 | sed -e '1,2d' | sed -n -e :a -e '1,3!{P;N;D;};N;ba' | gawk -f print_ip_mac.awk
