#!/bin/bash
# Grab an ARP list using arp-scan and chop off the top 2 lines and bottom 3 lines, Sort Ip address based on 3rd then 4th octet,
# finaly reformat with awk for JSON parsing print everything to Stdout
IFACE=$1
CWD=$2

IAB=$CWD/vendors/ieee-iab.txt
MAC=$CWD/vendors/mac.txt
OUI=$CWD/vendors/ieee-oui.txt

arp-scan --ouifile=$OUI --iabfile=$IAB --macfile=$MAC --ignoredups --localnet --interface=$1 | sed -e '1,2d' | sed -n -e :a -e '1,3!{P;N;D;};N;ba' | sort -t . -k 3,3n -k 4,4n | gawk -f $CWD/awk/print_ip_mac.awk
